### PR TITLE
Add secrets fixture

### PR DESCRIPTION
**Pull request by aaron-lane**
## Background

This PR adds a secrets fixture module and updates the nightly build tests to use it.

## How Has This Been Tested

It was tested with the backing configuration for the module CI tests. The tests here will consume those new secrets.

## This PR makes me feel

optional gif describing your feelings about this pr

### CODE REVIEW

**Comment by anniehedgpeth** [comment]
Hey @aaron-lane , is this ready for review? I wasn't sure if you were waiting on a passing test for Private TCP.

**Comment by aaron-lane** [comment]
@anniehedgpeth I forgot 😅 Let me investigate that failure first.

**Comment by aaron-lane** [comment]
@anniehedgpeth @sandrampeter this is now ready for review 🎉

**Review by sandrampeter — APPROVED** [review]

**Pull request merged**
