### PR TITLE
add FDO - Docker deployment option

### PR DESCRIPTION
**Pull request by anniehedgpeth**
## Background

Jira - [TF-8611](https://hashicorp.atlassian.net/browse/TF-8611)

Added necessary variables and config for FDO Docker deployment.

## How Has This Been Tested

- [x] there are 10 passing tests shown below in comments - 5 for Replicated and 5 for FDO
  - [x] FDO
    - [x] [private-active-active](https://github.com/hashicorp/terraform-google-terraform-enterprise/actions/runs/6854290023/job/18636883958)
    - [x] [private-tcp-active-active](https://github.com/hashicorp/terraform-google-terraform-enterprise/actions/runs/6854502641/job/18637584903)
    - [x] [public-active-active](https://github.com/hashicorp/terraform-google-terraform-enterprise/actions/runs/6818646469/job/18544589535)
    - [x] [standalone-mounted-disk](https://github.com/hashicorp/terraform-google-terraform-enterprise/actions/runs/6817658309/job/18541627388)
    - [x] [standalone-external-rhel8-worker](https://github.com/hashicorp/terraform-google-terraform-enterprise/actions/runs/6818247863/job/18543407097)
  - [x] Replicated
    - [x] [private-active-active-replicated](https://github.com/hashicorp/terraform-google-terraform-enterprise/actions/runs/6853428494/job/18634210302)
    - [x] [private-tcp-active-active-replicated](https://github.com/hashicorp/terraform-google-terraform-enterprise/actions/runs/6854287669/job/18636876692)
    - [x] [public-active-active-replicated](https://github.com/hashicorp/terraform-google-terraform-enterprise/actions/runs/6818645964/job/18544587869#step:23:2107)
    - [x] [standalone-mounted-disk-replicated](https://github.com/hashicorp/terraform-google-terraform-enterprise/actions/runs/6817658309/job/18541627783)
    - [x] [standalone-external-rhel8-worker-replicated](https://github.com/hashicorp/terraform-google-terraform-enterprise/actions/runs/6818249154/job/18543411039)
- [x] ptfe-replicated tests pass ([link](https://github.com/hashicorp/ptfe-replicated/actions/runs/6854531674))

## This PR makes me feel

finally

[TF-8611]: https://hashicorp.atlassian.net/browse/TF-8611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by amy-hashi — APPROVED** [review]
⭐ This looks great, thank you for all this work!

The only suggestion I have, that does not need to be addressed here, is some good examples with the new variables!

**Comment by anniehedgpeth** [comment]
> The only suggestion I have, that does not need to be addressed here, is some good examples with the new variables!

Yeah, I agree. I need to update the examples in all three modules. I will create a story for that now.

**Pull request merged**
