### PR TITLE
Add Public Active/Active test and switch from Cloud Storage to Secrets Manager

### PR DESCRIPTION
**Pull request by aaron-lane**
## Background

This branch adds the Public Active/Active test and switches the design to expect sensitve values as secrets rather than storing them in  buckets.

[Asana task](https://app.asana.com/0/1181500399442529/1200449299638580/f)

## How Has This Been Tested

It shall be tested here, live!

## This PR makes me feel

optional gif describing your feelings about this pr

### CODE REVIEW

**Comment by aaron-lane** [comment]
/test public-active-active

🤞🏼

**Review by anniehedgpeth — APPROVED** [review]

**Comment by aaron-lane** [comment]
/test all destroy=false

Welcome back, GitHub!

**Review by anniehedgpeth — APPROVED** [review]

**Pull request merged**
