### PR TITLE
Use transient workspaces for tests

### PR DESCRIPTION
**Pull request by aaron-lane**
## Background

This branch updates the module CI tests to use transient workspaces associated with the pull request number.

Relates #119

## How Has This Been Tested

...

### Test Configuration

* Terraform Version: 1.0.11
* Any additional relevant variables:

## This PR makes me feel

optional gif describing your feelings about this pr

### CODE REVIEW

**Comment by aaron-lane** [comment]
I verified that the private tests eventually came online, so from the perspective of these changes, the tests "passed" 🥵

**Comment by aaron-lane** [comment]
@anniehedgpeth this one is still waiting for a review when you have an opportunity.

**Comment by anniehedgpeth** [comment]
> @anniehedgpeth this one is still waiting for a review when you have an opportunity.

Ah thanks, this fell through the cracks.

**Review by anniehedgpeth — APPROVED** [review]
This is lovely! Excited to have this flexibility in our workspaces.

**Pull request merged**
